# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = QtQuickType
DESTDIR = ../x64/Debug
CONFIG += debug \
        qmltypes 
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += .
QML_IMPORT_NAME = quick.quicktype
QML_IMPORT_MAJOR_VERSION = 1
include(QtQuickType.pri)
